// Re-export Prisma client — generated by `prisma generate` from apps/api/prisma/schema.prisma
// Run `npm run prisma:generate` after any schema change.
export { PrismaClient } from './generated/prisma/client.js';
export type * from './generated/prisma/internal/prismaNamespace.js';

import { PrismaClient } from './generated/prisma/client.js';
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';

function createPrismaClient() {
  const pool = new Pool({ connectionString: process.env['DATABASE_URL'] });
  const adapter = new PrismaPg(pool);
  return new PrismaClient({ adapter });
}

// Singleton pattern — prevents multiple connections in dev (hot reload)
const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient };

export const prisma =
  globalForPrisma.prisma ?? createPrismaClient();

if (process.env['NODE_ENV'] !== 'production') {
  globalForPrisma.prisma = prisma;
}
